name: Run Tests

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      
      - name: Setup Nodejs
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #7.0.0
        with:
            node-version-file: ./services/node/api-node/package.json
            cache: 'npm'
            cache-dependency-path: ./services/node/api-node/package-lock.json
      - name: Setup Task
        uses: supplypike/setup-bin@8365380a806a88e7a0f0d07059b175ca2f5418d7 
        with:
            uri: 'https://github.com/go-task/task/releases/download/v3.53.1/task_linux_amd64.tar.gz'
            name: 'task'
            version: '3.53.1'
      - name : Install Deps
        working-directory: ./services/node/api-node
        run:  |
            task install

      - name : Run Tests
        working-directory: ./services/node/api-node
        run: |
            task test
